### ISSUE TITLE
alcid

### ISSUE THREAD

**Issue by starlifezzz** [Jasonzj/Hackintosh-EFI-Ryzen-MSI-B450I#2]
PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x4)  是05000000  不是50000000

**Comment by Jasonzj** [comment]
感谢哈， 我这一直没出现问题所以没注意到

**Comment by starlifezzz** [comment]
> 感谢哈， 我这一直没出现问题所以没注意到

这样就可以把设备属性里面的那个alcid=5删除掉了，不知道是不是心理感觉，感觉这样启动更快一点
