### ISSUE TITLE
虚拟机无法使用

### ISSUE THREAD

**Issue by najunuoyan** [Jasonzj/Hackintosh-EFI-Ryzen-MSI-B450I#6]
试了一下Parallels Desktop和Vmware Fusion，均无法正常开户虚拟机，网上找的办法也没解决，大神们有方案么？

**Comment by najunuoyan** [comment]
![image](https://user-images.githubusercontent.com/3922375/119254734-a7fc4000-bbea-11eb-83cd-12a2731aaa77.png)

**Comment by Jasonzj** [comment]
试下VirtualBox

**Comment by najunuoyan** [comment]
VirtualBox安装Win10正常，感谢
