### ISSUE TITLE
请问网卡是怎么转接的

### ISSUE THREAD

**Issue by najunuoyan** [Jasonzj/Hackintosh-EFI-Ryzen-MSI-B450I#7]
我买的1820A驱动不了，ReadMe中说"需转接卡替换主板原有模块 M.2 Key E"，请问能不能详细解释一下？想参照大佬的方案搞一下

**Comment by Jasonzj** [comment]
试下用 [AirportBrcmFixup](https://github.com/acidanthera/AirportBrcmFixup)和[BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM) 
我记得1820A不能免驱。

我用博通是这样转接
![install-boardcom-module-to-motherboard](https://user-images.githubusercontent.com/8412988/119981691-7fac8100-bff0-11eb-8886-cedb3bf77ba9.jpg)

**Comment by najunuoyan** [comment]
谢谢，我也试一下

**Comment by najunuoyan** [comment]
有需要的朋友可以参考：我把1820A换成了BCM94352Z，这个是短卡，不需要转接，也不会高出原来的卡托，驱动起来也不麻烦，教程在此：https://www.youtube.com/watch?v=PlA81wqN5OU&list=PLK7qLLDm2XKC91zcPuTmzvhj1bgpBDvXE&index=2&ab_channel=TechLabs
当然，最省心的还是找个免驱卡吧

**Comment by najunuoyan** [comment]
> 有需要的朋友可以参考：我把1820A换成了BCM94352Z，这个是短卡，不需要转接，也不会高出原来的卡托，驱动起来也不麻烦，教程在此：https://www.youtube.com/watch?v=PlA81wqN5OU&list=PLK7qLLDm2XKC91zcPuTmzvhj1bgpBDvXE&index=2&ab_channel=TechLabs
> 当然，最省心的还是找个免驱卡吧

最终用了跟@Jasonzj 一模一样的方案，睡眠和随航不行，其他都OK

**Comment by najunuoyan** [comment]
> > 有需要的朋友可以参考：我把1820A换成了BCM94352Z，这个是短卡，不需要转接，也不会高出原来的卡托，驱动起来也不麻烦，教程在此：https://www.youtube.com/watch?v=PlA81wqN5OU&list=PLK7qLLDm2XKC91zcPuTmzvhj1bgpBDvXE&index=2&ab_channel=TechLabs
> > 当然，最省心的还是找个免驱卡吧
> 
> 最终用了跟@Jasonzj 一模一样的方案，睡眠和随航不行，其他都OK

将HDMI换成DP线之后睡眠也正常了
