### ISSUE TITLE
请问CPU型号显示为未知该如何解决

### ISSUE THREAD

**Issue by najunuoyan** [Jasonzj/Hackintosh-EFI-Ryzen-MSI-B450I#8]
如题，CPU是amd 3600.
在网上也搜索了方法，OC的platforminfo中processortype一直都是0，请问大佬有没有解决方法。
![11628314961_ pic](https://user-images.githubusercontent.com/3922375/128589466-8cffeb0b-857d-42c9-bfae-af5f2992100e.jpg)
![21628315054_ pic](https://user-images.githubusercontent.com/3922375/128589506-dc80311e-c885-47b6-8971-3771ce48b082.jpg)

**Comment by Jasonzj** [comment]
这个要修改/System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/Resources里的cpu信息。
本来可以通过关闭 SIP 更改 system 文件夹为可写入，BigSur后都被苹果禁止了，你想弄的话可以试试: [https://www.zhihu.com/question/403361335/answer/1583471375](
https://www.zhihu.com/question/403361335/answer/1583471375)
我这也是显示Intel的，不过觉得没什么影响就没弄了

**Comment by najunuoyan** [comment]
看了一下方法，有点绕，big sur下还是不折腾了，谢谢指点
